// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * A console command which we will try to execute inside Rocket League.
 * See https://github.com/RLBot/RLBot/wiki/Console-Commands for a list of known commands.
 */
export class ConsoleCommand {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):ConsoleCommand {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsConsoleCommand(bb:flatbuffers.ByteBuffer, obj?:ConsoleCommand):ConsoleCommand {
  return (obj || new ConsoleCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsConsoleCommand(bb:flatbuffers.ByteBuffer, obj?:ConsoleCommand):ConsoleCommand {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new ConsoleCommand()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

command():string|null
command(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
command(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

static startConsoleCommand(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addCommand(builder:flatbuffers.Builder, commandOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, commandOffset, 0);
}

static endConsoleCommand(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createConsoleCommand(builder:flatbuffers.Builder, commandOffset:flatbuffers.Offset):flatbuffers.Offset {
  ConsoleCommand.startConsoleCommand(builder);
  ConsoleCommand.addCommand(builder, commandOffset);
  return ConsoleCommand.endConsoleCommand(builder);
}

unpack(): ConsoleCommandT {
  return new ConsoleCommandT(
    this.command()
  );
}


unpackTo(_o: ConsoleCommandT): void {
  _o.command = this.command();
}
}

export class ConsoleCommandT {
constructor(
  public command: string|Uint8Array|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const command = (this.command !== null ? builder.createString(this.command!) : 0);

  return ConsoleCommand.createConsoleCommand(builder,
    command
  );
}
}
