// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { ControllerState, ControllerStateT } from '../../rlbot/flat/controller-state';


/**
 * Rocket League is notifying us that some player has moved their controller. This is an *output*
 */
export class PlayerInputChange {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PlayerInputChange {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPlayerInputChange(bb:flatbuffers.ByteBuffer, obj?:PlayerInputChange):PlayerInputChange {
  return (obj || new PlayerInputChange()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPlayerInputChange(bb:flatbuffers.ByteBuffer, obj?:PlayerInputChange):PlayerInputChange {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PlayerInputChange()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

playerIndex():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

controllerState(obj?:ControllerState):ControllerState|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new ControllerState()).__init(this.bb!.__indirect(this.bb_pos + offset), this.bb!) : null;
}

dodgeForward():number {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

dodgeRight():number {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPlayerInputChange(builder:flatbuffers.Builder) {
  builder.startObject(4);
}

static addPlayerIndex(builder:flatbuffers.Builder, playerIndex:number) {
  builder.addFieldInt32(0, playerIndex, 0);
}

static addControllerState(builder:flatbuffers.Builder, controllerStateOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, controllerStateOffset, 0);
}

static addDodgeForward(builder:flatbuffers.Builder, dodgeForward:number) {
  builder.addFieldFloat32(2, dodgeForward, 0.0);
}

static addDodgeRight(builder:flatbuffers.Builder, dodgeRight:number) {
  builder.addFieldFloat32(3, dodgeRight, 0.0);
}

static endPlayerInputChange(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): PlayerInputChangeT {
  return new PlayerInputChangeT(
    this.playerIndex(),
    (this.controllerState() !== null ? this.controllerState()!.unpack() : null),
    this.dodgeForward(),
    this.dodgeRight()
  );
}


unpackTo(_o: PlayerInputChangeT): void {
  _o.playerIndex = this.playerIndex();
  _o.controllerState = (this.controllerState() !== null ? this.controllerState()!.unpack() : null);
  _o.dodgeForward = this.dodgeForward();
  _o.dodgeRight = this.dodgeRight();
}
}

export class PlayerInputChangeT {
constructor(
  public playerIndex: number = 0,
  public controllerState: ControllerStateT|null = null,
  public dodgeForward: number = 0.0,
  public dodgeRight: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  const controllerState = (this.controllerState !== null ? this.controllerState!.pack(builder) : 0);

  PlayerInputChange.startPlayerInputChange(builder);
  PlayerInputChange.addPlayerIndex(builder, this.playerIndex);
  PlayerInputChange.addControllerState(builder, controllerState);
  PlayerInputChange.addDodgeForward(builder, this.dodgeForward);
  PlayerInputChange.addDodgeRight(builder, this.dodgeRight);

  return PlayerInputChange.endPlayerInputChange(builder);
}
}
