// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * A psyonix bot, e.g. All Star bot
 */
export class PsyonixBotPlayer {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):PsyonixBotPlayer {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsPsyonixBotPlayer(bb:flatbuffers.ByteBuffer, obj?:PsyonixBotPlayer):PsyonixBotPlayer {
  return (obj || new PsyonixBotPlayer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsPsyonixBotPlayer(bb:flatbuffers.ByteBuffer, obj?:PsyonixBotPlayer):PsyonixBotPlayer {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new PsyonixBotPlayer()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

botSkill():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readFloat32(this.bb_pos + offset) : 0.0;
}

static startPsyonixBotPlayer(builder:flatbuffers.Builder) {
  builder.startObject(1);
}

static addBotSkill(builder:flatbuffers.Builder, botSkill:number) {
  builder.addFieldFloat32(0, botSkill, 0.0);
}

static endPsyonixBotPlayer(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}

static createPsyonixBotPlayer(builder:flatbuffers.Builder, botSkill:number):flatbuffers.Offset {
  PsyonixBotPlayer.startPsyonixBotPlayer(builder);
  PsyonixBotPlayer.addBotSkill(builder, botSkill);
  return PsyonixBotPlayer.endPsyonixBotPlayer(builder);
}

unpack(): PsyonixBotPlayerT {
  return new PsyonixBotPlayerT(
    this.botSkill()
  );
}


unpackTo(_o: PsyonixBotPlayerT): void {
  _o.botSkill = this.botSkill();
}
}

export class PsyonixBotPlayerT {
constructor(
  public botSkill: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return PsyonixBotPlayer.createPsyonixBotPlayer(builder,
    this.botSkill
  );
}
}
