// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';



/**
 * Expresses the rotation state of an object.
 * Learn about quaternions here: https://en.wikipedia.org/wiki/Quaternions_and_spatial_rotation
 * You can tinker with them here to build an intuition: https://quaternions.online/
 */
export class Quaternion {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):Quaternion {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

x():number {
  return this.bb!.readFloat32(this.bb_pos);
}

y():number {
  return this.bb!.readFloat32(this.bb_pos + 4);
}

z():number {
  return this.bb!.readFloat32(this.bb_pos + 8);
}

w():number {
  return this.bb!.readFloat32(this.bb_pos + 12);
}

static sizeOf():number {
  return 16;
}

static createQuaternion(builder:flatbuffers.Builder, x: number, y: number, z: number, w: number):flatbuffers.Offset {
  builder.prep(4, 16);
  builder.writeFloat32(w);
  builder.writeFloat32(z);
  builder.writeFloat32(y);
  builder.writeFloat32(x);
  return builder.offset();
}


unpack(): QuaternionT {
  return new QuaternionT(
    this.x(),
    this.y(),
    this.z(),
    this.w()
  );
}


unpackTo(_o: QuaternionT): void {
  _o.x = this.x();
  _o.y = this.y();
  _o.z = this.z();
  _o.w = this.w();
}
}

export class QuaternionT {
constructor(
  public x: number = 0.0,
  public y: number = 0.0,
  public z: number = 0.0,
  public w: number = 0.0
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  return Quaternion.createQuaternion(builder,
    this.x,
    this.y,
    this.z,
    this.w
  );
}
}
