// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Quaternion, QuaternionT } from '../../rlbot/flat/quaternion';
import { Vector3, Vector3T } from '../../rlbot/flat/vector3';


/**
 * The state of a rigid body in Rocket League's physics engine.
 * This gets updated in time with the physics tick, not the rendering framerate.
 * The frame field will be incremented every time the physics engine ticks.
 */
export class RigidBodyState {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):RigidBodyState {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsRigidBodyState(bb:flatbuffers.ByteBuffer, obj?:RigidBodyState):RigidBodyState {
  return (obj || new RigidBodyState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsRigidBodyState(bb:flatbuffers.ByteBuffer, obj?:RigidBodyState):RigidBodyState {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new RigidBodyState()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

frame():number {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.readInt32(this.bb_pos + offset) : 0;
}

location(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

rotation(obj?:Quaternion):Quaternion|null {
  const offset = this.bb!.__offset(this.bb_pos, 8);
  return offset ? (obj || new Quaternion()).__init(this.bb_pos + offset, this.bb!) : null;
}

velocity(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 10);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

angularVelocity(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 12);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startRigidBodyState(builder:flatbuffers.Builder) {
  builder.startObject(5);
}

static addFrame(builder:flatbuffers.Builder, frame:number) {
  builder.addFieldInt32(0, frame, 0);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, locationOffset, 0);
}

static addRotation(builder:flatbuffers.Builder, rotationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(2, rotationOffset, 0);
}

static addVelocity(builder:flatbuffers.Builder, velocityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(3, velocityOffset, 0);
}

static addAngularVelocity(builder:flatbuffers.Builder, angularVelocityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(4, angularVelocityOffset, 0);
}

static endRigidBodyState(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): RigidBodyStateT {
  return new RigidBodyStateT(
    this.frame(),
    (this.location() !== null ? this.location()!.unpack() : null),
    (this.rotation() !== null ? this.rotation()!.unpack() : null),
    (this.velocity() !== null ? this.velocity()!.unpack() : null),
    (this.angularVelocity() !== null ? this.angularVelocity()!.unpack() : null)
  );
}


unpackTo(_o: RigidBodyStateT): void {
  _o.frame = this.frame();
  _o.location = (this.location() !== null ? this.location()!.unpack() : null);
  _o.rotation = (this.rotation() !== null ? this.rotation()!.unpack() : null);
  _o.velocity = (this.velocity() !== null ? this.velocity()!.unpack() : null);
  _o.angularVelocity = (this.angularVelocity() !== null ? this.angularVelocity()!.unpack() : null);
}
}

export class RigidBodyStateT {
constructor(
  public frame: number = 0,
  public location: Vector3T|null = null,
  public rotation: QuaternionT|null = null,
  public velocity: Vector3T|null = null,
  public angularVelocity: Vector3T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  RigidBodyState.startRigidBodyState(builder);
  RigidBodyState.addFrame(builder, this.frame);
  RigidBodyState.addLocation(builder, (this.location !== null ? this.location!.pack(builder) : 0));
  RigidBodyState.addRotation(builder, (this.rotation !== null ? this.rotation!.pack(builder) : 0));
  RigidBodyState.addVelocity(builder, (this.velocity !== null ? this.velocity!.pack(builder) : 0));
  RigidBodyState.addAngularVelocity(builder, (this.angularVelocity !== null ? this.angularVelocity!.pack(builder) : 0));

  return RigidBodyState.endRigidBodyState(builder);
}
}
