// automatically generated by the FlatBuffers compiler, do not modify

import * as flatbuffers from 'flatbuffers';

import { Vector3, Vector3T } from '../../rlbot/flat/vector3';


/**
 * A minimal version of the ball, useful when bandwidth needs to be conserved.
 */
export class TinyBall {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):TinyBall {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsTinyBall(bb:flatbuffers.ByteBuffer, obj?:TinyBall):TinyBall {
  return (obj || new TinyBall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsTinyBall(bb:flatbuffers.ByteBuffer, obj?:TinyBall):TinyBall {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new TinyBall()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

location(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

velocity(obj?:Vector3):Vector3|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? (obj || new Vector3()).__init(this.bb_pos + offset, this.bb!) : null;
}

static startTinyBall(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addLocation(builder:flatbuffers.Builder, locationOffset:flatbuffers.Offset) {
  builder.addFieldStruct(0, locationOffset, 0);
}

static addVelocity(builder:flatbuffers.Builder, velocityOffset:flatbuffers.Offset) {
  builder.addFieldStruct(1, velocityOffset, 0);
}

static endTinyBall(builder:flatbuffers.Builder):flatbuffers.Offset {
  const offset = builder.endObject();
  return offset;
}


unpack(): TinyBallT {
  return new TinyBallT(
    (this.location() !== null ? this.location()!.unpack() : null),
    (this.velocity() !== null ? this.velocity()!.unpack() : null)
  );
}


unpackTo(_o: TinyBallT): void {
  _o.location = (this.location() !== null ? this.location()!.unpack() : null);
  _o.velocity = (this.velocity() !== null ? this.velocity()!.unpack() : null);
}
}

export class TinyBallT {
constructor(
  public location: Vector3T|null = null,
  public velocity: Vector3T|null = null
){}


pack(builder:flatbuffers.Builder): flatbuffers.Offset {
  TinyBall.startTinyBall(builder);
  TinyBall.addLocation(builder, (this.location !== null ? this.location!.pack(builder) : 0));
  TinyBall.addVelocity(builder, (this.velocity !== null ? this.velocity!.pack(builder) : 0));

  return TinyBall.endTinyBall(builder);
}
}
